import type { Agent, HubState, WorkItem, WorkStatus } from "./types";
export function seed(): HubState {
  const at = "2026-09-21T02:30:00.000Z";
  const agents: Agent[] = [
    {
      id: "urs",
      name: "URS Navigator",
      lv1: "MES Engineering",
      lv2: "요구사항 분석",
      summary:
        "현장의 요청을 명확한 요구사항으로. 질문과 대화를 통해 필요한 정보를 함께 정리합니다.",
      owner: "staff",
      status: "open",
      intake: true,
      color: "#256b58",
      examples: [
        "설비 상태 이력 조회 요구사항을 정리해 주세요.",
        "업무 목적과 예외 조건을 함께 검토하고 싶어요.",
      ],
      checklist: [
        "비즈니스 목적 확인",
        "요구사항과 예외 조건 정리",
        "요청자 검토 반영",
      ],
    },
    {
      id: "fds",
      name: "FDS Architect",
      lv1: "MES Engineering",
      lv2: "기능 설계",
      summary:
        "요구사항과 시스템 맥락을 연결해 검토 가능한 기능 명세를 설계합니다.",
      owner: "staff",
      status: "open",
      intake: false,
      color: "#5275a6",
      examples: ["전달받은 URS를 바탕으로 기능 명세 초안을 작성해 주세요."],
      checklist: [
        "입력 요구사항 확인",
        "기능과 데이터 매핑 검토",
        "예외 처리 명세 작성",
      ],
    },
    {
      id: "test",
      name: "Test Companion",
      lv1: "Quality & Validation",
      lv2: "테스트 설계",
      summary:
        "명세에서 테스트 조건을 찾아 정상·예외 시나리오를 빠짐없이 구성합니다.",
      owner: "admin",
      status: "open",
      intake: false,
      color: "#ad7541",
      examples: ["설비 상태 전이별 테스트 시나리오를 만들어 주세요."],
      checklist: [
        "요구사항 추적성 확인",
        "정상·예외 시나리오 작성",
        "기대 결과 명시",
      ],
    },
    {
      id: "gmp",
      name: "GMP Reviewer",
      lv1: "Quality & Validation",
      lv2: "프로토콜 검토",
      summary:
        "테스트 프로토콜의 검토 포인트를 정리하고 보완할 근거 자료를 찾습니다.",
      owner: "admin",
      status: "working",
      intake: false,
      color: "#8865a6",
      examples: ["이 프로토콜에서 보완할 검토 포인트를 정리해 주세요."],
      checklist: ["프로토콜 검토", "증빙 자료 연결", "담당자 최종 확인"],
    },
    {
      id: "deploy",
      name: "Release Desk",
      lv1: "Operations",
      lv2: "배포 확인",
      summary:
        "수동 배포의 기록과 확인 자료를 한곳에. 변경 결과와 검증 메모를 남깁니다.",
      owner: "staff",
      status: "open",
      intake: false,
      color: "#687884",
      examples: ["배포 후 확인할 항목을 정리합니다."],
      checklist: ["배포 담당자 확인", "타겟 반영 확인", "검증 자료 첨부"],
    },
    {
      id: "legacy",
      name: "ET Legacy Helper",
      lv1: "MES Engineering",
      lv2: "이전 버전",
      summary:
        "이전 ET 분석 업무와 자료를 조회할 수 있는 보관용 에이전트입니다.",
      owner: "staff",
      status: "retired",
      intake: false,
      color: "#87918b",
      examples: [],
      checklist: ["기존 자료 확인"],
    },
  ].map((a) => ({
    ...a,
    link1: "",
    link2: "",
    connectionMode: a.id === "deploy" ? "external" : "api",
    profileId: "internal",
    defaultModel: "",
    ...a,
  })) as Agent[];
  const defs: [string, string, string, string, WorkStatus][] = [
    [
      "urs-work",
      "urs",
      "설비 상태 이력 조회 개선",
      "생산 현장의 설비 상태 변경 이력을 조건별로 조회하고 근거 자료로 내보내는 요청입니다.",
      "active",
    ],
    [
      "fds-work",
      "fds",
      "ET 상태 조회 기능 명세",
      "URS 검토 결과를 바탕으로 조회 조건, 표시 항목과 예외 처리를 설계합니다.",
      "review",
    ],
    [
      "test-work",
      "test",
      "설비 상태 전이 테스트",
      "상태 전이와 권한별 테스트 시나리오 및 기대 결과를 준비합니다.",
      "active",
    ],
    [
      "gmp-work",
      "gmp",
      "ET 프로토콜 사전 검토",
      "작성된 프로토콜의 추적성과 증빙 자료를 확인합니다.",
      "waiting",
    ],
    [
      "deploy-work",
      "deploy",
      "ET 설정 반영 확인",
      "담당자가 수동 배포 후 조회 결과와 확인 자료를 기록합니다.",
      "waiting",
    ],
    [
      "urs-clean",
      "urs",
      "세척 주기 알림 요구사항",
      "세척 유효기간 만료 전 알림 시점과 대상자를 확인합니다.",
      "waiting",
    ],
    [
      "fds-done",
      "fds",
      "장비 사용 이력 내보내기",
      "CSV 내보내기 항목과 조회 범위 명세 작성을 마쳤습니다.",
      "done",
    ],
    [
      "legacy-work",
      "legacy",
      "이전 ET 조회 개선 검토",
      "이전 버전의 논의와 검토 기록입니다.",
      "done",
    ],
  ];
  const works: WorkItem[] = defs.map(
    ([id, agentId, title, description, status], i) => ({
      id,
      agentId,
      title,
      description,
      status,
      owner: i === 2 || i === 3 ? "admin" : "staff",
      createdBy: i === 0 ? "requester" : "staff",
      createdAt: at,
      updatedAt: at,
      archived: false,
      manual: agentId === "deploy",
      externalUrl: "",
      checks: agents
        .find((a) => a.id === agentId)!
        .checklist.map((label, j) => ({
          id: `${id}-check-${j}`,
          label,
          done: status === "done" || (j === 0 && status !== "waiting"),
        })),
      notes: [],
      inputIds: id === "urs-work" ? ["requirements-v1"] : [],
      outputIds: id === "fds-work" ? ["fds-v1"] : [],
      activeThreadId: `${id}-thread`,
    }),
  );
  return {
    version: 1,
    users: [
      { id: "staff", name: "김민준", team: "MES Engineering" },
      { id: "requester", name: "이서연", team: "Manufacturing" },
      { id: "admin", name: "박지훈", team: "Platform Admin" },
    ],
    session: { userId: "staff", role: "staff" },
    agents,
    profiles: [
      {
        id: "internal",
        name: "사내 AI · 데모 연결",
        mode: "demo",
        baseUrl: "",
        chatPath: "/chat/completions",
        modelsPath: "/models",
        models: ["glm-5.2", "internal-reasoning"],
        defaultModel: "glm-5.2",
        sendNames: false,
      },
    ],
    works,
    threads: works.map((w) => ({
      id: w.activeThreadId,
      workId: w.id,
      title: w.id === "urs-work" ? "요구사항 함께 정리하기" : "첫 번째 대화",
      createdAt: at,
      model: "",
      srIds: w.id === "urs-work" ? ["sr-example"] : [],
      activeBundleIds: [],
    })),
    messages: [
      {
        id: "urs-m1",
        threadId: "urs-work-thread",
        role: "user",
        actor: "requester",
        content:
          "설비의 상태 변경 이력을 날짜와 설비 ID로 조회하고 싶습니다. 변경 사유와 작업자도 함께 확인해야 합니다.",
        at,
        kind: "request",
        source: "human",
        contextIds: [],
        fileIds: ["requirements-v1"],
      },
      {
        id: "urs-m2",
        visibleToRequester: "requester",
        threadId: "urs-work-thread",
        role: "assistant",
        actor: "urs",
        content:
          "요청을 정리했습니다.\n\n1. 조회 조건: 설비 ID, 조회 기간, 상태\n2. 결과 항목: 변경 전·후 상태, 변경 시각, 작업자, 변경 사유\n3. 추가 확인: 조회 권한과 최대 조회 기간이 정해져 있나요?\n\n확인된 내용만 요구사항으로 구분하고, 미정 항목은 따로 남기겠습니다.",
        at,
        kind: "reply",
        source: "demo",
        model: "glm-5.2",
        contextIds: [],
        fileIds: [],
      },
      {
        id: "urs-m3",
        threadId: "urs-work-thread",
        role: "user",
        actor: "staff",
        content:
          "운영 담당자와 QA에 조회 권한이 필요합니다. 기본 조회 기간은 최근 30일이며 CSV 내보내기를 포함해 주세요.",
        at,
        kind: "discussion",
        source: "human",
        contextIds: [],
        fileIds: [],
      },
      {
        id: "fds-m1",
        threadId: "fds-work-thread",
        role: "user",
        actor: "staff",
        content:
          "설비 상태 조회의 입력 검증과 결과 표시 항목을 기능 명세로 정리해 주세요.",
        at,
        kind: "request",
        source: "human",
        contextIds: [],
        fileIds: [],
      },
      {
        id: "fds-m2",
        threadId: "fds-work-thread",
        role: "assistant",
        actor: "fds",
        content:
          "기능 명세 초안\n\n• 시작일은 종료일보다 늦을 수 없습니다.\n• 조회 권한을 가진 사용자에게 설비 상태 이력을 표시합니다.\n• 결과가 없는 경우 조회 조건을 유지하고 빈 결과 안내를 표시합니다.\n• 내보내기에는 현재 조회 조건과 조회 시각을 포함합니다.\n\n최대 조회 기간과 CSV 최대 건수는 담당자 확인이 필요합니다.",
        at,
        kind: "reply",
        source: "demo",
        model: "glm-5.2",
        contextIds: [],
        fileIds: [],
      },
    ],
    artifacts: [
      {
        id: "requirements-v1",
        workId: "urs-work",
        name: "ET_요구사항_메모.txt",
        mime: "text/plain",
        size: 190,
        version: 1,
        createdBy: "requester",
        createdAt: at,
        content:
          "설비 상태 이력 조회 요청\n조회 조건: 설비 ID, 기간, 상태\n표시 항목: 변경 전후 상태, 변경 시각, 변경 사유, 작업자\n미정 사항: 최대 조회 기간, CSV 최대 건수",
      },
      {
        id: "fds-v1",
        workId: "fds-work",
        name: "FDS_상태조회_초안.md",
        mime: "text/markdown",
        size: 140,
        version: 1,
        createdBy: "staff",
        createdAt: at,
        content:
          "# ET 상태 조회 기능 명세\n\n조회 조건 검증 후 상태 이력과 작업자 정보를 표시합니다.\n빈 결과와 권한 오류를 별도로 안내합니다.\n\n## 검토 필요\n- 최대 조회 기간\n- 내보내기 건수 제한",
      },
    ],
    bundles: [],
    handoffs: [],
    requests: [
      {
        id: "sr-example",
        number: "SR-2026-0001",
        title: "설비 상태 이력 조회 개선",
        requester: "requester",
        workId: "urs-work",
        threadId: "urs-work-thread",
        status: "received",
        createdAt: at,
        submittedAt: at,
        results: [],
      },
    ],
    activities: works.map((w) => ({
      id: `act-${w.id}`,
      workId: w.id,
      actor: w.createdBy,
      at,
      action: "업무 생성",
      detail: w.title,
    })),
    notifications: [
      {
        id: "notice-seed",
        userId: "staff",
        title: "새 SR이 접수되었습니다",
        body: "SR-2026-0001 · 설비 상태 이력 조회 개선",
        link: "#/requests/sr-example",
        at,
        read: false,
      },
    ],
  };
}
